### ISSUE TITLE
How to predict/inference using the model?

### ISSUE THREAD

**Issue by gokul427** [haonan-li/MultiSpanQA#4]
Hi,

I am new to using transformer models. Can you please help me how to make predictions after fine tuning the model.

Thanks,

**Comment by haonan-li** [comment]
Hi 

If you have a 'test.json' file, add the flag --do-predict, it will do prediction on the file automatically.
See code in 'run_tagger.py'

`if training_args.do_predict:
        data_files['test'] = os.path.join(data_args.data_dir, "test.json")`
