### ISSUE TITLE
The code of the model proposed in your paper.

### ISSUE THREAD

**Issue by island-jie** [haonan-li/MultiSpanQA#7]
Excuse me, I am also researching the multi-span QA recently.  I need to reproduce the model of your paper.  Would you please publish the source code of the model proposed in your paper?
I hope to get your reply, thank you!

**Comment by haonan-li** [comment]
All code provided:
code -> result in paper
run_squad.py -> single (v1, v2) baselines
run_tagger.py -> tagger baseline
run_tagger_plus.py -> tagger (joint, full)

**Comment by island-jie** [comment]
Thank you !
These days, I've reproduced  the model proposed in your paper, while when I use Roberta-large, I found that the training loss and valid loss have not decreased, I have been troubled by this for several days . 
Can you help me to use Roberta-large in runTaggerPlus.py ?
Best wishes!

**Comment by haonan-li** [comment]
Sorry but I am busy recently, and cannot update with Roberta support in a short term.
